version: '3'
services:
  fakhaama:
    container_name: fakhaama
    build: './fakhaama'
    image: fakhaama
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: fakhaama
      DB_USER: root
      DB_PASSWORD: root
      STORAGE_API_KEY: $2y$10$r/lSPkvm3my/Hg0fn1ADO.0S.lIP7C3xydWsAsTt/fY/7.qozk/su
      STORAGE_URL: storage
      STORAGE_PORT: 9090
    ports:
      - 80:3000
    depends_on:
      database:
        condition: service_healthy

  dashboard:
    container_name: dashboard
    build: './dashboard'
    image: dashboard
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: fakhaama
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - 9000:9000
    depends_on:
      database:
        condition: service_healthy

  storage:
    container_name: storage
    build: './storage'
    image: storage
    environment:
      PORT: 9090
      KEY: $2y$10$r/lSPkvm3my/Hg0fn1ADO.0S.lIP7C3xydWsAsTt/fY/7.qozk/su
    ports:
      - 9090:9090
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: fakhaama
    ports:
      - 5432:5432
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
